# Lab 1: Transformations with NumPy
You are now in a Jupyter notebook! It consists of written text, mixed with executable Python code.

You are supposed to read from top to bottom, and fill in code in the Python-blocks as you go.

## 1. Getting started
Familiarize yourself with the [NumPy quickstart](https://numpy.org/doc/stable/user/quickstart.html). You will need it to solve the following tasks.
Use the text, examples and links in the quickstart guide.

## 2. Get familiar with NumPy
First, import NumPy:

Press `Shift + Enter` to execute and advance to the next block. Repeat for each block. You can click on a block to edit and run the code again.
Press `Ctrl + Enter` to execute the current block without advancing.

In [3]:
import numpy as np

## a) Create vectors and matrices
#### Create vector `t`

$\mathbf{t} =
\begin{bmatrix}
1 \\
0 \\
3
\end{bmatrix}
$

Hint: [https://numpy.org/doc/stable/user/quickstart.html#array-creation](https://numpy.org/doc/stable/user/quickstart.html#array-creation)

In [61]:
# TODO: Create vector `t`
t = None
print(f"t = {t}\nshape: {t.shape}\ntype: {type(t)}")

t = [1 0 3]
shape: (3,)
type: <class 'numpy.ndarray'>


It's important to note that the sequence of numbers in a one-dimensional NumPy "vector", like `np.array([1, 2, 3])`, is just numbers in a vector space and therefore neither a row nor a column-vector. We can see that its shape is `(3,)`.

In order to use it with linear algebra, we have to explicitly go for a 2D representation.

#### Try to create `t` as a `N x 1` _column_ vector.


In [62]:
# TODO: Create 't' as a 'N x 1' column vector

print(f"\nt = \n{t}\nshape: {t.shape}")

Explicit
row = [[1 2 3]], shape: (1, 3)
col = 
[[1]
 [2]
 [3]], shape: (3, 1)

Transpose:
col2 = 
[[1]
 [2]
 [3]], shape: (3, 1)

Shortcuts
row = [[1 2 3]], shape: (1, 3)
col = 
[[1]
 [2]
 [3]], shape: (3, 1)

Reshape
row = [[0 1 2 3 4 5 6 7]], shape: (1, 8)
col = 
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]], shape: (8, 1)

Increase dimension
row = [[1 2 3]], shape: (1, 3)
col = 
[[1]
 [2]
 [3]], shape: (3, 1)

t = 
[[1]
 [0]
 [3]]
shape: (3, 1)


#### Create matrix `A`

$
\mathbf{A} =
\begin{bmatrix}
1 & 0 & 3\\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
$

In [5]:
# TODO: Create matrix A
A = None
print(f"A:\n{A}")

A:
None


#### Create identity matrix I.

$
\mathbf{I}=
\begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
$

Hint: [https://numpy.org/doc/stable/user/quickstart.html#functions-and-methods-overview](https://numpy.org/doc/stable/user/quickstart.html#functions-and-methods-overview)

In [6]:
# TODO: Create matrix I
I = None
print(f"I:\n{I}")

I:
None



#### Create matrix T.

$
\mathbf{T} =
\begin{bmatrix}
\mathbf{A} & \mathbf{t} \\
\mathbf{0} & 1
\end{bmatrix}
$

Hint: [https://numpy.org/doc/stable/user/quickstart.html#stacking-together-different-arrays](https://numpy.org/doc/stable/user/quickstart.html#stacking-together-different-arrays)
Hint: [https://numpy.org/doc/stable/reference/generated/numpy.block.html](https://numpy.org/doc/stable/reference/generated/numpy.block.html)

In [8]:
# TODO: Create T
T = None
print(f"T:\n{T}")

T:
None


#### Create matrix B.

$
\mathbf{B} = \mathbf{A}^T
$

Hint: [https://numpy.org/doc/stable/user/quickstart.html#changing-the-shape-of-an-array](https://numpy.org/doc/stable/user/quickstart.html#changing-the-shape-of-an-array)

In [9]:
# Todo: B
B = None
print(f"A = \n{A}\nB = \n{B}")

A = 
None
B = 
None


## b) Coefficients
Set $t_2 = 2$ and $A_{12} = 2$, so that

   $\mathbf{t} =
    \begin{bmatrix}
    1 \\
    2 \\
    3
    \end{bmatrix},
    \:
    \mathbf{A} =
    \begin{bmatrix}
    1 & 2 & 3\\
    4 & 5 & 6 \\
    7 & 8 & 9
    \end{bmatrix}$

Perform the corresponding corrections to **T**, so that we still have

   $\mathbf{T} =
    \begin{bmatrix}
    \mathbf{A} & \mathbf{t} \\
    \mathbf{0} & 1
    \end{bmatrix}$

But hey, what happened to **B**?

In [10]:
# TODO: Solve b)
print(f"t:\n{t}\nA:\n{A},\nB:\n{B}")

t:
None
A:
None,
B:
None


## c) Block operations
Extract the row vector

$\mathbf{r}_2 = \begin{bmatrix}A_{21} & A_{22} & A_{23}\end{bmatrix}$

and the column vector

$\mathbf{c}_2 = \begin{bmatrix}A_{12} \\ A_{22} \\ A_{32} \end{bmatrix}$

from **A**.

Extract the submatrix

$\mathbf{T}_{3 \times 4} = \begin{bmatrix}\mathbf{A} & \mathbf{t}\end{bmatrix}$

from **T**.

In [11]:
# TODO: r_2
r_2 = None
# TODO: c_2
c_2 = None
# TODO: T_3x4
T_3x4 = None

Set the corresponding blocks in **A** and **T** to all `0` (so that the second row and column in **A** are all 0, and the upper 3x4 matrix in **T** is all 0).

Hint: [https://numpy.org/doc/stable/user/quickstart.html#copies-and-views](https://numpy.org/doc/stable/user/quickstart.html#copies-and-views)

In [12]:
# TODO set 0

print(f"A = \n{A}")
print(f"T = \n{T}")

A = 
None
T = 
None


## d) Matrix and vector arithmetic
- Add two vectors
- Add two matrices
- Multiply two matrices
- Take the dot product between two vectors
- Take the coefficient-wise multiplication between two matrices

Hint: [https://numpy.org/doc/stable/user/quickstart.html#basic-operations](https://numpy.org/doc/stable/user/quickstart.html#basic-operations)

In [13]:
v1 = None
v2 = None
M = None
N = None
print(f"v1: {v1}\nv2: {v2}\n")
print(f"M:\n{M}\nN:\n{N}\n")

print(f"v1 + v2 = {v1 + v2}\n")

print(f"M + N = \n{M + N}\n")

print(f"(M+N) * M =\n{(M+N) @ M}\n")

print(f"v1 dot v2 = {v1.dot(v2)}")

print(f"Element-wise M * N =\n{M * N}")


v1: None
v2: None

M:
None
N:
None



TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'

## e) Reductions
- Take the sum of all elements in a matrix
- Compute the minimum value in a matrix
    - Also, find its position in the matrix
- Create a vector that is the maximum of each column in a matrix
- Find the L2-norm of a vector
- Find the number of elements in a vector that is greater than a given value.

In [15]:
# Replace 'None' with valid expressions

# TODO: Take the sum of all elements in a matrix
# https://numpy.org/doc/stable/user/quickstart.html#basic-operations
print(f"sum of A: {None}")

# TODO: Compute the minimum value in a matrix
# TODO: Also, find its position in the matrix.
print(f"minimum of A: {None} "
      f"at index {None}, "
      f"(or {None} in 2D)")

# TODO: Create a vector that is the maximum of each column in a matrix.
print(f"maximum of each column in A: {None}")

# TODO: Find the L2-norm of a vector.
v1 = None
print(f"L2 norm of {v1} is {None}")

# TODO: Find the number of elements in a vector that is greater than a given value.
# https://numpy.org/doc/stable/user/quickstart.html#changing-the-shape-of-an-array
v2 = None
print(f"v2: {v2},\n"
      f"    {None} elements are greater than 10")

sum of A: None
minimum of A: None at index None, (or None in 2D)
maximum of each column in A: None
L2 norm of None is None
v2: None,
    None elements are greater than 10


Now that you have gotten to know NumPy, let's use it to transform images in the [next part of the lab](lab_01_transformations.ipynb)!