# Lab 1: Transformations with NumPy
You are now in a Jupyter notebook! It consists of written text, mixed with executable Python code.

You are supposed to read from top to bottom, and fill in code in the Python-blocks as you go.

## 1. Getting started
Familiarize yourself with the [NumPy quickstart](https://numpy.org/doc/stable/user/quickstart.html). You will need it to solve the following tasks!
Use the text, examples and links in the quickstart guide.

## 2. Get familiar with NumPy
First, import NumPy:

Press `Shift + Enter` to execute and advance to the next block. Repeat for each block. You can click on a block to edit and run the code again.

In [47]:
import numpy as np

## a) Create vectors and matrices

![a1](../lab-guide/img/a-create-vectors-math.png)

![a2](../lab-guide/img/a-create-vectors-math-2.png)



#### Create vector `t`
Hint: [https://numpy.org/doc/stable/user/quickstart.html#array-creation](https://numpy.org/doc/stable/user/quickstart.html#array-creation)

In [44]:
# TODO: Create vector `t`
t = np.array([1, 0, 3])
print(f"t = {t}\nshape: {t.shape}\ntype: {type(t)}")

t = [1 0 3]
shape: (3,)
type: <class 'numpy.ndarray'>


It's important to note that the sequence of numbers in a one-dimensional NumPy "vector", like `np.array([1, 2, 3])`, is just numbers in a vector space and therefore neither a row nor a column-vector. We can see that its shape is `(3,)`.

In order to use it with linear algebra, we have to explicitly go for a 2D representation.

#### Try to create `t` as a `N x 1` _column_ vector.


In [54]:
# TODO: Create 't' as a 'N x 1' column vector
# i) Be explicit
row = np.array([[1, 2, 3]])               # 1 row with 3 elements. Note the double brackets.
col = np.array([[1],[2],[3]])             # 3 rows with 1 element each
print("i)")
print(f"row = {row}, shape: {row.shape}")
print(f"col = \n{col}, shape: {col.shape}")

# ii) Use shortcuts
row = np.r_['r', [1,2,3]]                 # shape: (1, 3)
col = np.r_['c', [1,2,3]]                 # shape: (3,1)
print("\nii)")
print(f"row = {row}, shape: {row.shape}")
print(f"col = \n{col}, shape: {col.shape}")

# iii)
col = np.array([1, 2, 3])[:, None]        # stores in rows
row = np.array([1, 2, 3])[None, :]        # stores in columns
print("\niii)")
print(f"row = {row}, shape: {row.shape}")
print(f"col = \n{col}, shape: {col.shape}")

# iv) Reshape
col = np.array([1, 2, 3]).reshape(-1, 1)  # Reshape to change the 'view' of the data
row = np.array([1, 2, 3]).reshape(1, -1)  # Reshape to change the 'view' of the data
t = np.array([1, 2, 3])
t.shape = (-1, 1)                         # Set the shape later
print("\niv)")
print(f"row = {row}, shape: {row.shape}")
print(f"col = \n{col}, shape: {col.shape}")
print(f"t = \n{t}, shape: {t.shape}")

# v) Use ndmin
row = np.array([1, 2, 3], ndmin=2)          # shape: (1, 3)
print("\nv)")
print(f"row = {row}, shape: {row.shape}")

i)
row = [[1 2 3]], shape: (1, 3)
col = 
[[1]
 [2]
 [3]], shape: (3, 1)

ii)
row = [[1 2 3]], shape: (1, 3)
col = 
[[1]
 [2]
 [3]], shape: (3, 1)

iii)
row = [[1 2 3]], shape: (1, 3)
col = 
[[1]
 [2]
 [3]], shape: (3, 1)

iv)
row = [[1 2 3]], shape: (1, 3)
col = 
[[1]
 [2]
 [3]], shape: (3, 1)
t = 
[[1]
 [2]
 [3]], shape: (3, 1)

v)
row = [[1 2 3]], shape: (1, 3)


#### Create matrix `A`

In [55]:
# TODO: Create matrix A
A = np.array([[1, 0, 3],
              [4, 5, 6],
              [7, 8, 9]])

#### Create identity matrix I.
Hint: [https://numpy.org/doc/stable/user/quickstart.html#functions-and-methods-overview](https://numpy.org/doc/stable/user/quickstart.html#functions-and-methods-overview)

In [56]:
# TODO: Create matrix I
I = np.eye(3)


#### Create matrix T.
Hint: [https://numpy.org/doc/stable/user/quickstart.html#stacking-together-different-arrays](https://numpy.org/doc/stable/user/quickstart.html#stacking-together-different-arrays)
Hint: [https://numpy.org/doc/stable/reference/generated/numpy.block.html](https://numpy.org/doc/stable/reference/generated/numpy.block.html)

In [57]:
# TODO: Create matrix T
T1 = np.row_stack((np.c_[A, t], [0, 0, 0, 1]))  # Nested stacking
T2 = np.block([                                 # Using 'block'
    [A, t],
    [0, 0, 0, 1]
])
print(f"T2 = \n{T2}\nnp.array_equal(T1, T2): {np.array_equal(T1, T2)}")

T2 = 
[[1 0 3 1]
 [4 5 6 2]
 [7 8 9 3]
 [0 0 0 1]]
np.array_equal(T1, T2): True


#### Create matrix B.
Hint: [https://numpy.org/doc/stable/user/quickstart.html#changing-the-shape-of-an-array](https://numpy.org/doc/stable/user/quickstart.html#changing-the-shape-of-an-array)

In [58]:
B = A.T
print(f"A = \n{A}\nB = \n{B}")

A = 
[[1 0 3]
 [4 5 6]
 [7 8 9]]
B = 
[[1 4 7]
 [0 5 8]
 [3 6 9]]


## b) Coefficients
Set $t_2 = 2$ and $A_{12} = 2$, so that

   ![b1](../lab-guide/img/b-coefficients-math.png)

Perform the corresponding corrections to **T**, so that we still have

   ![b2](../lab-guide/img/b-coefficients-math-T.png)

In [59]:
# Todo: B
# Note python is zero indexed, so t_2 is t[1]
t[1] = 2

# In the matrix the indexes are A[row, col]
A[0, 1] = 2

## c) Block operations
Extract the row vector

![c1](../lab-guide/img/c-row-vector-from-A.png)

and the column vector

![c2](../lab-guide/img/c-col-vector-from-A.png)

from **A**.

Extract the submatrix

![c3](../lab-guide/img/c-submatrix-T.png)

from **T**.

In [60]:
# TODO: r_2
# TODO: c_2
r_2 = A[1, :]
c_2 = A[:, 1]
# TODO: T_3x4
T = T2
T_3x4 = T[0:3]

Set the corresponding blocks in **A** and **T** to all `0` (so that the second row and column in **A** are all 0, and the upper 3x4 matrix in **T** is all 0).

Hint: [https://numpy.org/doc/stable/user/quickstart.html#copies-and-views](https://numpy.org/doc/stable/user/quickstart.html#copies-and-views)

In [61]:
# TODO
r_2[:] = 0
c_2[:] = 0
T_3x4[:] = 0
print(f"A = \n{A}")
print(f"T = \n{T}")

A = 
[[1 0 3]
 [0 0 0]
 [7 0 9]]
T = 
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]]


## d) Matrix and vector arithmetic
- Add two vectors
- Add two matrices
- Multiply two matrices
- Take the dot product between two vectors
- Take the coefficient-wise multiplication between two matrices

Hint: [https://numpy.org/doc/stable/user/quickstart.html#basic-operations](https://numpy.org/doc/stable/user/quickstart.html#basic-operations)

In [62]:
v1 = np.array([1, 2, 3])
v2 = np.array([3, 2, 1])
print(f"v1: {v1}\nv2: {v2}")
print(f"v1 + v2 = {v1 + v2}")
print(f"A + I = \n{A + I}")
print(f"(A+I) * T_3x4 =\n{(A+I) @ T_3x4}")
print(f"v1.transpose() * v2 = {v1.transpose() * v2}")
print(f"v1.transpose() @ v2 = {v1.transpose() @ v2}")
print(f"v1.dot(v2) = {v1.dot(v2)}")
print(f"Element-wise B * I =\n{B * I}")


v1: [1 2 3]
v2: [3 2 1]
v1 + v2 = [4 4 4]
A + I = 
[[ 2.  0.  3.]
 [ 0.  1.  0.]
 [ 7.  0. 10.]]
(A+I) * T_3x4 =
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
v1.transpose() * v2 = [3 4 3]
v1.transpose() @ v2 = 10
v1.dot(v2) = 10
Element-wise B * I =
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 9.]]


## e) Reductions
- Take the sum of all elements in a matrix
- Compute the minimum value in a matrix
    - Also, find its position in the matrix
- Create a vector that is the maximum of each column in a matrix
- Find the L2-norm of a vector
- Find the number of elements in a vector that is greater than a given value.

In [63]:
A = np.arange(10, 19).reshape(3, 3)
A[2, 2] = 5
print(f"A:\n{A}")

# TODO: Take the sum of all elements in a matrix
# https://numpy.org/doc/stable/user/quickstart.html#basic-operations
print(f"sum of A: {A.sum()}")

# TODO: Compute the minimum value in a matrix
# TODO: Also, find its position in the matrix.
print(f"minimum of A: {A.min()} at index {A.argmin()}, or {np.unravel_index(A.argmin(), A.shape)}")

# TODO: Create a vector that is the maximum of each column in a matrix.
print(f"maximum of each column in A: {A.max(0)}")

# TODO: Find the L2-norm of a vector.
v = np.array([1, 1])
print(f"L2 norm of {v} is {np.linalg.norm(v)}")

# TODO: Find the number of elements in a vector that is greater than a given value.
# https://numpy.org/doc/stable/user/quickstart.html#changing-the-shape-of-an-array
v = np.array([0, 10, 2, 13, 4, 15, 6, 17, 8, 19])
print(f"v: {v}, greater than 10: {(v > 10).sum()}")

A:
[[10 11 12]
 [13 14 15]
 [16 17  5]]
sum of A: 113
minimum of A: 5 at index 8, or (2, 2)
maximum of each column in A: [16 17 15]
L2 norm of [1 1] is 1.4142135623730951
v: [ 0 10  2 13  4 15  6 17  8 19], greater than 10: 4


Now that you have gotten to know NumPy, let's use it to transform images in the next part of the lab!